builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    goamd64:
      - v1
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archives:
  - files:
      - config.json
